### ISSUE TITLE
Mistake in Example

### ISSUE THREAD

**Issue by geoffjukes** [onefinestay/nameko-sqlalchemy#18]
Hi Matt,
In the example, should:
```
from nameko_sqlalchemy import Session
```
be
```
from nameko_sqlalchemy import Database
```
?

**Comment by mattbennett** [comment]
Hey Geoff,

Thanks for pointing this out. The README is definitely wrong.

Since #16 landed, there are actually two DependencyProviders -- a new one called `Database`, and the original one called `DatabaseSession` (which actually used to be called simply `Session`, hence the mistake in the README).

We kept `DatabaseSession` for backwards compatibility but I think the API in the newer DP is far superior: it's lazy (more efficient), more granular, and includes a context manager for auto-commit. You can get a good idea of how it operates by looking at the tests:

https://github.com/onefinestay/nameko-sqlalchemy/blob/3456a981d8afe4e5e3f68aa08238b087235b2dba/test/test_database.py#L157-L286

**Comment by mattbennett** [comment]
This is fixed in master now.
